[Feature/navigation] : Add Android Navigation
TeamPophory/pophory-android-sdk pull request #30
Opened 2023-06-30 06:05 UTC by KwakEuiJin

## 변경 사항

- Naviation Library 추가
- Onboard Page 추가
- PathUtil Object -> Class 변경

## 참고사항
- 인생네컷 플로우 따라가는 Sample앱 만들고자 화면과 라이브러리 추가했습니다.

2023-06-30 06:23 UTC, l2hyunwoo requested changes

2023-06-30 06:23 UTC, l2hyunwoo commented on app/build.gradle.kts
> +    alias(libs.plugins.kotlinAndroid)
이미 share.application에 있습니다.

2023-06-30 06:23 UTC, l2hyunwoo commented on app/build.gradle.kts
> +    implementation(libs.material)
얘도 마찬가지

2023-06-30 06:23 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/share/presentation/onboard/OnboardActivity.kt
> +        setContentView(R.layout.activity_onboard)
```suggestion
        setContentView(binding.root)
```

2023-06-30 06:23 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/share/presentation/onboard/fragment/LogoFragment.kt
> +        fun newInstance(param1: String, param2: String) =
지금 구현상황에서 param1, param2 받을 필요가 있을까?

2023-06-30 06:23 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/share/presentation/onboard/fragment/SpecifyAmountFragment.kt
> +    private var _binding: FragmentSpecifyAmountBinding? = null
onDestroyView에서 해제하는 로직 추가!

2023-06-30 06:23 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/share/util/PathUtil.kt
> +class PathUtil {
클래스로 전환의 목적은 함수를 호출할 때 필요한 input만 넣으면 원하는 output이 나오게 하려는데에 있어. 지금 보면 굳이 함수의 param으로 받지 않아도 될 것 들이 좀 많은 것 같아. 이 부분 구현 다시 생각해보는 것도 좋을 것 같음

2023-06-30 06:28 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/share/presentation/onboard/fragment/SpecifyAmountFragment.kt
> +    private var _binding: FragmentSpecifyAmountBinding? = null
앗 까먹었다!!

2023-06-30 06:28 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/share/presentation/onboard/fragment/LogoFragment.kt
> +        fun newInstance(param1: String, param2: String) =
없습니다 바로 지울게요

2023-06-30 06:29 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/share/presentation/onboard/OnboardActivity.kt
> +        setContentView(R.layout.activity_onboard)
섬세하지 못한 코드 죄송함다..

2023-06-30 06:32 UTC, KwakEuiJin commented on app/build.gradle.kts
> +    alias(libs.plugins.kotlinAndroid)
오 해당 부분 삭제하겠습니다.

2023-07-13 04:47 UTC, l2hyunwoo approved these changes

2023-07-13 07:22 UTC, merged